# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Wurlf
version:      1.00
version_from: lib/Mobile/Wurfl.pm
installdirs:  site
requires:
    CGI::Lite:                     0
    Data::Dumper:                  0
    DBD::CSV:                      0
    DBI:                           0
    ExtUtils::MakeMaker:           0
    File::Find:                    1.07
    File::Path:                    0
    File::Slurp:                   0
    FindBin:                       0
    LWP::Simple:                   0
    Test::More:                    0
    XML::Simple:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
